### ISSUE TITLE
BaseCodec doesn't work with Python < 3.10

### ISSUE THREAD

**Issue by MystPi** [yuwex/scratchcloud#2]
`list[str]` is invalid Python < 3.10 and results in a syntax error. I know the docs say that it is for Python 3.10, but the readme/PyPi says it's for 3.8, 3.9, and 3.10. 

[![PyPi Package Python Versions](https://shields.io/pypi/pyversions/scratchcloud)](https://pypi.org/project/scratchcloud/)
https://github.com/yuwex/scratchcloud/blob/603addc69c1e33fc12b6c64b998cb6cf189385f1/scratchcloud/ext/codecs.py#L19

**Comment by yuwex** [comment]
Ah thanks! I totally forgot that I made that change. I'll update the versions on pypi to be for 3.10 only.

**Comment by yuwex** [comment]
Resolved by https://github.com/yuwex/scratchcloud/commit/5f4d46e4023e51706698c36f823578c4b52ba2a2 :) Thanks for opening the first issue 🎉
